<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EditionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $editions = [
            ['id' => '1', 'identifier' => 'ar.muyassar', 'language' => 'ar', 'name' => 'تفسير المیسر', 'english_name' => 'King Fahad Quran Complex', 'format' => 'text', 'type' => 'tafsir', 'direction' => 'rtl'],
            ['id' => '2', 'identifier' => 'az.mammadaliyev', 'language' => 'az', 'name' => 'Məmmədəliyev & Bünyadov', 'english_name' => 'Vasim Mammadaliyev and Ziya Bunyadov', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '3', 'identifier' => 'az.musayev', 'language' => 'az', 'name' => 'Musayev', 'english_name' => 'Alikhan Musayev', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '4', 'identifier' => 'bn.bengali', 'language' => 'bn', 'name' => 'মুহিউদ্দীন খান', 'english_name' => 'Muhiuddin Khan', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '5', 'identifier' => 'cs.hrbek', 'language' => 'cs', 'name' => 'Hrbek', 'english_name' => 'Preklad I. Hrbek', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '6', 'identifier' => 'cs.nykl', 'language' => 'cs', 'name' => 'Nykl', 'english_name' => 'A. R. Nykl', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '7', 'identifier' => 'de.aburida', 'language' => 'de', 'name' => 'Abu Rida', 'english_name' => 'Abu Rida Muhammad ibn Ahmad ibn Rassoul', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '8', 'identifier' => 'de.bubenheim', 'language' => 'de', 'name' => 'Bubenheim & Elyas', 'english_name' => 'A. S. F. Bubenheim and N. Elyas', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '9', 'identifier' => 'de.khoury', 'language' => 'de', 'name' => 'Khoury', 'english_name' => 'Adel Theodor Khoury', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '10', 'identifier' => 'de.zaidan', 'language' => 'de', 'name' => 'Zaidan', 'english_name' => 'Amir Zaidan', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '11', 'identifier' => 'dv.divehi', 'language' => 'dv', 'name' => 'ދިވެހި', 'english_name' => 'Office of the President of Maldives', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '12', 'identifier' => 'en.ahmedali', 'language' => 'en', 'name' => 'Ahmed Ali', 'english_name' => 'Ahmed Ali', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '13', 'identifier' => 'en.ahmedraza', 'language' => 'en', 'name' => 'Ahmed Raza Khan', 'english_name' => 'Ahmed Raza Khan', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '14', 'identifier' => 'en.arberry', 'language' => 'en', 'name' => 'Arberry', 'english_name' => 'A. J. Arberry', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '15', 'identifier' => 'en.asad', 'language' => 'en', 'name' => 'Asad', 'english_name' => 'Muhammad Asad', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '16', 'identifier' => 'en.daryabadi', 'language' => 'en', 'name' => 'Daryabadi', 'english_name' => 'Abdul Majid Daryabadi', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '17', 'identifier' => 'en.hilali', 'language' => 'en', 'name' => 'Hilali & Khan', 'english_name' => 'Muhammad Taqi-ud-Din al-Hilali and Muhammad Muhsin Khan', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '18', 'identifier' => 'en.pickthall', 'language' => 'en', 'name' => 'Pickthall', 'english_name' => 'Mohammed Marmaduke William Pickthall', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '19', 'identifier' => 'en.qaribullah', 'language' => 'en', 'name' => 'Qaribullah & Darwish', 'english_name' => 'Hasan al-Fatih Qaribullah and Ahmad Darwish', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '20', 'identifier' => 'en.sahih', 'language' => 'en', 'name' => 'Saheeh International', 'english_name' => 'Saheeh International', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '21', 'identifier' => 'en.sarwar', 'language' => 'en', 'name' => 'Sarwar', 'english_name' => 'Muhammad Sarwar', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '22', 'identifier' => 'en.yusufali', 'language' => 'en', 'name' => 'Yusuf Ali', 'english_name' => 'Abdullah Yusuf Ali', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '23', 'identifier' => 'fa.ayati', 'language' => 'fa', 'name' => 'آیتی', 'english_name' => 'AbdolMohammad Ayati', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '24', 'identifier' => 'fa.fooladvand', 'language' => 'fa', 'name' => 'فولادوند', 'english_name' => 'Mohammad Mahdi Fooladvand', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '25', 'identifier' => 'fa.ghomshei', 'language' => 'fa', 'name' => 'الهی قمشه‌ای', 'english_name' => 'Mahdi Elahi Ghomshei', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '26', 'identifier' => 'fa.makarem', 'language' => 'fa', 'name' => 'مکارم شیرازی', 'english_name' => 'Naser Makarem Shirazi', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '27', 'identifier' => 'fr.hamidullah', 'language' => 'fr', 'name' => 'Hamidullah', 'english_name' => 'Muhammad Hamidullah', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '28', 'identifier' => 'ha.gumi', 'language' => 'ha', 'name' => 'Gumi', 'english_name' => 'Abubakar Mahmoud Gumi', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '29', 'identifier' => 'hi.hindi', 'language' => 'hi', 'name' => 'फ़ारूक़ ख़ान & नदवी', 'english_name' => 'Suhel Farooq Khan and Saifur Rahman Nadwi', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '30', 'identifier' => 'id.indonesian', 'language' => 'id', 'name' => 'Bahasa Indonesia', 'english_name' => 'Unknown', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '31', 'identifier' => 'it.piccardo', 'language' => 'it', 'name' => 'Piccardo', 'english_name' => 'Hamza Roberto Piccardo', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '32', 'identifier' => 'ja.japanese', 'language' => 'ja', 'name' => 'Japanese', 'english_name' => 'Unknown', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '33', 'identifier' => 'ko.korean', 'language' => 'ko', 'name' => 'Korean', 'english_name' => 'Unknown', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '34', 'identifier' => 'ku.asan', 'language' => 'ku', 'name' => 'ته‌فسیری ئاسان', 'english_name' => 'Burhan Muhammad-Amin', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '35', 'identifier' => 'ml.abdulhameed', 'language' => 'ml', 'name' => 'അബ്ദുല്‍ ഹമീദ് & പറപ്പൂര്‍', 'english_name' => 'Cheriyamundam Abdul Hameed and Kunhi Mohammed Parappoor', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '36', 'identifier' => 'nl.keyzer', 'language' => 'nl', 'name' => 'Keyzer', 'english_name' => 'Salomo Keyzer', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '37', 'identifier' => 'no.berg', 'language' => 'no', 'name' => 'Einar Berg', 'english_name' => 'Einar Berg', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '38', 'identifier' => 'pl.bielawskiego', 'language' => 'pl', 'name' => 'Bielawskiego', 'english_name' => 'Józefa Bielawskiego', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '39', 'identifier' => 'pt.elhayek', 'language' => 'pt', 'name' => 'El-Hayek', 'english_name' => 'Samir El-Hayek', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '40', 'identifier' => 'ro.grigore', 'language' => 'ro', 'name' => 'Grigore', 'english_name' => 'George Grigore', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '41', 'identifier' => 'ru.kuliev', 'language' => 'ru', 'name' => 'Кулиев', 'english_name' => 'Elmir Kuliev', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '42', 'identifier' => 'ru.osmanov', 'language' => 'ru', 'name' => 'Османов', 'english_name' => 'Magomed-Nuri Osmanovich Osmanov', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '43', 'identifier' => 'ru.porokhova', 'language' => 'ru', 'name' => 'Порохова', 'english_name' => 'V. Porokhova', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '44', 'identifier' => 'sd.amroti', 'language' => 'sd', 'name' => 'امروٽي', 'english_name' => 'Taj Mehmood Amroti', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '45', 'identifier' => 'so.abduh', 'language' => 'so', 'name' => 'Abduh', 'english_name' => 'Mahmud Muhammad Abduh', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '46', 'identifier' => 'sq.ahmeti', 'language' => 'sq', 'name' => 'Sherif Ahmeti', 'english_name' => 'Sherif Ahmeti', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '47', 'identifier' => 'sq.mehdiu', 'language' => 'sq', 'name' => 'Feti Mehdiu', 'english_name' => 'Feti Mehdiu', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '48', 'identifier' => 'sq.nahi', 'language' => 'sq', 'name' => 'Efendi Nahi', 'english_name' => 'Hasan Efendi Nahi', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '49', 'identifier' => 'sv.bernstrom', 'language' => 'sv', 'name' => 'Bernström', 'english_name' => 'Knut Bernström', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '50', 'identifier' => 'sw.barwani', 'language' => 'sw', 'name' => 'Al-Barwani', 'english_name' => 'Ali Muhsin Al-Barwani', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '51', 'identifier' => 'ta.tamil', 'language' => 'ta', 'name' => 'ஜான் டிரஸ்ட்', 'english_name' => 'Jan Turst Foundation', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '52', 'identifier' => 'tg.ayati', 'language' => 'tg', 'name' => 'Оятӣ', 'english_name' => 'AbdolMohammad Ayati', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '53', 'identifier' => 'th.thai', 'language' => 'th', 'name' => 'ภาษาไทย', 'english_name' => 'King Fahad Quran Complex', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '54', 'identifier' => 'tr.ates', 'language' => 'tr', 'name' => 'Süleyman Ateş', 'english_name' => 'Suleyman Ates', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '55', 'identifier' => 'tr.bulac', 'language' => 'tr', 'name' => 'Alİ Bulaç', 'english_name' => 'Alİ Bulaç', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '56', 'identifier' => 'tr.diyanet', 'language' => 'tr', 'name' => 'Diyanet İşleri', 'english_name' => 'Diyanet Isleri', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '57', 'identifier' => 'tr.golpinarli', 'language' => 'tr', 'name' => 'Abdulbakî Gölpınarlı', 'english_name' => 'Abdulbaki Golpinarli', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '58', 'identifier' => 'tr.ozturk', 'language' => 'tr', 'name' => 'Öztürk', 'english_name' => 'Yasar Nuri Ozturk', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '59', 'identifier' => 'tr.transliteration', 'language' => 'tr', 'name' => 'Çeviriyazı', 'english_name' => 'Muhammet Abay', 'format' => 'text', 'type' => 'transliteration', 'direction' => 'ltr'],
            ['id' => '60', 'identifier' => 'tr.vakfi', 'language' => 'tr', 'name' => 'Diyanet Vakfı', 'english_name' => 'Diyanet Vakfi', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '61', 'identifier' => 'tr.yazir', 'language' => 'tr', 'name' => 'Elmalılı Hamdi Yazır', 'english_name' => 'Elmalili Hamdi Yazir', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '62', 'identifier' => 'tr.yildirim', 'language' => 'tr', 'name' => 'Suat Yıldırım', 'english_name' => 'Suat Yildirim', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '63', 'identifier' => 'tr.yuksel', 'language' => 'tr', 'name' => 'Edip Yüksel', 'english_name' => 'Edip Yüksel', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '64', 'identifier' => 'tt.nugman', 'language' => 'tt', 'name' => 'Yakub Ibn Nugman', 'english_name' => 'Yakub Ibn Nugman', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '65', 'identifier' => 'ug.saleh', 'language' => 'ug', 'name' => 'محمد صالح', 'english_name' => 'Muhammad Saleh', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '66', 'identifier' => 'ur.ahmedali', 'language' => 'ur', 'name' => 'احمد علی', 'english_name' => 'Ahmed Ali', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '67', 'identifier' => 'ur.jalandhry', 'language' => 'ur', 'name' => 'جالندہری', 'english_name' => 'Fateh Muhammad Jalandhry', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '68', 'identifier' => 'ur.jawadi', 'language' => 'ur', 'name' => 'علامہ جوادی', 'english_name' => 'Syed Zeeshan Haider Jawadi', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '69', 'identifier' => 'ur.kanzuliman', 'language' => 'ur', 'name' => 'احمد رضا خان', 'english_name' => 'Ahmed Raza Khan', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '70', 'identifier' => 'ur.qadri', 'language' => 'ur', 'name' => 'طاہر القادری', 'english_name' => 'Tahir ul Qadri', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '71', 'identifier' => 'uz.sodik', 'language' => 'uz', 'name' => 'Мухаммад Содик', 'english_name' => 'Muhammad Sodik Muhammad Yusuf', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '72', 'identifier' => 'en.maududi', 'language' => 'en', 'name' => 'Maududi', 'english_name' => 'Abul Ala Maududi', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '73', 'identifier' => 'en.shakir', 'language' => 'en', 'name' => 'Shakir', 'english_name' => 'Mohammad Habib Shakir', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '74', 'identifier' => 'en.transliteration', 'language' => 'en', 'name' => 'Transliteration', 'english_name' => 'English Transliteration', 'format' => 'text', 'type' => 'transliteration', 'direction' => 'ltr'],
            ['id' => '75', 'identifier' => 'es.cortes', 'language' => 'es', 'name' => 'Cortes', 'english_name' => 'Julio Cortes', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '76', 'identifier' => 'fa.ansarian', 'language' => 'fa', 'name' => 'انصاریان', 'english_name' => 'Hussain Ansarian', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '77', 'identifier' => 'quran-simple', 'language' => 'ar', 'name' => 'القرآن الكريم المبسط (تشكيل بسيط] (simple]', 'english_name' => 'Simple', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '78', 'identifier' => 'quran-simple-clean', 'language' => 'ar', 'name' => 'القرآن الكريم المبسط (بدون تشكيل] (simple-clean]', 'english_name' => 'Simple Clean', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '79', 'identifier' => 'quran-simple-enhanced', 'language' => 'ar', 'name' => 'القرآن الكريم المبسط (بدون تشكيل] (simple-enhanced]', 'english_name' => 'Simple Enhanced', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '80', 'identifier' => 'quran-simple-min', 'language' => 'ar', 'name' => 'القرآن الكريم المبسط (بدون تشكيل] (simple-min]', 'english_name' => 'Simple Minimal', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '81', 'identifier' => 'quran-uthmani-min', 'language' => 'ar', 'name' => 'القرآن الكريم برسم العثماني (تشكيل بسيط] (uthmani-min]', 'english_name' => 'Uthmani Minimal', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '82', 'identifier' => 'quran-uthmani', 'language' => 'ar', 'name' => 'القرآن الكريم برسم العثماني (uthmani]', 'english_name' => 'Uthmani', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '83', 'identifier' => 'bg.theophanov', 'language' => 'bg', 'name' => 'Теофанов', 'english_name' => 'Tzvetan Theophanov', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '84', 'identifier' => 'bs.mlivo', 'language' => 'bs', 'name' => 'Mlivo', 'english_name' => 'Mustafa Mlivo', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '85', 'identifier' => 'fa.bahrampour', 'language' => 'fa', 'name' => 'بهرام پور', 'english_name' => 'Abolfazl Bahrampour', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '86', 'identifier' => 'es.asad', 'language' => 'es', 'name' => 'Asad', 'english_name' => 'Muhammad Asad - Abdurrasak Pérez', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '87', 'identifier' => 'fa.khorramshahi', 'language' => 'fa', 'name' => 'خرمشاهی', 'english_name' => 'Baha\'oddin Khorramshahi', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '88', 'identifier' => 'fa.mojtabavi', 'language' => 'fa', 'name' => 'مجتبوی', 'english_name' => 'Sayyed Jalaloddin Mojtabavi', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '89', 'identifier' => 'hi.farooq', 'language' => 'hi', 'name' => 'फ़ारूक़ ख़ान & अहमद', 'english_name' => 'Muhammad Farooq Khan and Muhammad Ahmed', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '90', 'identifier' => 'id.muntakhab', 'language' => 'id', 'name' => 'Quraish Shihab', 'english_name' => 'Muhammad Quraish Shihab et al.', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '91', 'identifier' => 'ms.basmeih', 'language' => 'ms', 'name' => 'Basmeih', 'english_name' => 'Abdullah Muhammad Basmeih', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '92', 'identifier' => 'ru.abuadel', 'language' => 'ru', 'name' => 'Абу Адель', 'english_name' => 'Abu Adel', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '93', 'identifier' => 'ru.krachkovsky', 'language' => 'ru', 'name' => 'Крачковский', 'english_name' => 'Ignaty Yulianovich Krachkovsky', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '94', 'identifier' => 'ru.muntahab', 'language' => 'ru', 'name' => 'Аль-Мунтахаб', 'english_name' => 'Ministry of Awqaf, Egypt', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '95', 'identifier' => 'ru.sablukov', 'language' => 'ru', 'name' => 'Саблуков', 'english_name' => 'Gordy Semyonovich Sablukov', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '96', 'identifier' => 'ur.junagarhi', 'language' => 'ur', 'name' => 'محمد جوناگڑھی', 'english_name' => 'Muhammad Junagarhi', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '97', 'identifier' => 'ur.maududi', 'language' => 'ur', 'name' => 'ابوالاعلی مودودی', 'english_name' => 'Abul A\'ala Maududi', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '98', 'identifier' => 'zh.jian', 'language' => 'zh', 'name' => 'Ma Jian', 'english_name' => 'Ma Jian', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '99', 'identifier' => 'zh.majian', 'language' => 'zh', 'name' => 'Ma Jian (Traditional]', 'english_name' => 'Ma Jian', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '100', 'identifier' => 'fa.khorramdel', 'language' => 'fa', 'name' => 'خرمدل', 'english_name' => 'Mostafa Khorramdel', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '101', 'identifier' => 'fa.moezzi', 'language' => 'fa', 'name' => 'معزی', 'english_name' => 'Mohammad Kazem Moezzi', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '102', 'identifier' => 'bs.korkut', 'language' => 'bs', 'name' => 'Korkut', 'english_name' => 'Besim Korkut', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '103', 'identifier' => 'ar.jalalayn', 'language' => 'ar', 'name' => 'تفسير الجلالين', 'english_name' => 'Jalal ad-Din al-Mahalli and Jalal ad-Din as-Suyuti', 'format' => 'text', 'type' => 'tafsir', 'direction' => 'rtl'],
            ['id' => '104', 'identifier' => 'quran-tajweed', 'language' => 'ar', 'name' => 'القرآن الكريم المجود (ملون] (tajweed]', 'english_name' => 'Tajweed', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '105', 'identifier' => 'quran-wordbyword', 'language' => 'ar', 'name' => 'معاني مفردات القرآن (wordbyword]', 'english_name' => 'Word By Word', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '106', 'identifier' => 'ar.abdulbasitmurattal', 'language' => 'ar', 'name' => 'عبد الباسط عبد الصمد المرتل', 'english_name' => 'Abdul Basit', 'format' => 'audio', 'type' => 'translation', 'direction' => null],
            ['id' => '107', 'identifier' => 'ar.abdullahbasfar', 'language' => 'ar', 'name' => 'عبد الله بصفر', 'english_name' => 'Abdullah Basfar', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '108', 'identifier' => 'ar.abdurrahmaansudais', 'language' => 'ar', 'name' => 'عبدالرحمن السديس', 'english_name' => 'Abdurrahmaan As-Sudais', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '109', 'identifier' => 'ar.abdulsamad', 'language' => 'ar', 'name' => 'عبدالباسط عبدالصمد', 'english_name' => 'Abdul Samad', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '110', 'identifier' => 'ar.shaatree', 'language' => 'ar', 'name' => 'أبو بكر الشاطري', 'english_name' => 'Abu Bakr Ash-Shaatree', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '111', 'identifier' => 'ar.ahmedajamy', 'language' => 'ar', 'name' => 'أحمد بن علي العجمي', 'english_name' => 'Ahmed ibn Ali al-Ajamy', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '112', 'identifier' => 'ar.alafasy', 'language' => 'ar', 'name' => 'مشاري العفاسي', 'english_name' => 'Alafasy', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '113', 'identifier' => 'ar.hanirifai', 'language' => 'ar', 'name' => 'هاني الرفاعي', 'english_name' => 'Hani Rifai', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '114', 'identifier' => 'ar.husary', 'language' => 'ar', 'name' => 'محمود خليل الحصري', 'english_name' => 'Husary', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '115', 'identifier' => 'ar.husarymujawwad', 'language' => 'ar', 'name' => 'محمود خليل الحصري (المجود]', 'english_name' => 'Husary (Mujawwad]', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '116', 'identifier' => 'ar.hudhaify', 'language' => 'ar', 'name' => 'علي بن عبدالرحمن الحذيفي', 'english_name' => 'Hudhaify', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '117', 'identifier' => 'ar.ibrahimakhbar', 'language' => 'ar', 'name' => 'إبراهيم الأخضر', 'english_name' => 'Ibrahim Akhdar', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '118', 'identifier' => 'ar.mahermuaiqly', 'language' => 'ar', 'name' => 'ماهر المعيقلي', 'english_name' => 'Maher Al Muaiqly', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '119', 'identifier' => 'ar.minshawi', 'language' => 'ar', 'name' => 'محمد صديق المنشاوي', 'english_name' => 'Minshawi', 'format' => 'audio', 'type' => 'translation', 'direction' => null],
            ['id' => '120', 'identifier' => 'ar.minshawimujawwad', 'language' => 'ar', 'name' => 'محمد صديق المنشاوي (المجود]', 'english_name' => 'Minshawy (Mujawwad]', 'format' => 'audio', 'type' => 'translation', 'direction' => null],
            ['id' => '121', 'identifier' => 'ar.muhammadayyoub', 'language' => 'ar', 'name' => 'محمد أيوب', 'english_name' => 'Muhammad Ayyoub', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '122', 'identifier' => 'ar.muhammadjibreel', 'language' => 'ar', 'name' => 'محمد جبريل', 'english_name' => 'Muhammad Jibreel', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '123', 'identifier' => 'ar.saoodshuraym', 'language' => 'ar', 'name' => 'سعود الشريم', 'english_name' => 'Saood bin Ibraaheem Ash-Shuraym', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '124', 'identifier' => 'en.walk', 'language' => 'en', 'name' => 'Ibrahim Walk', 'english_name' => 'Ibrahim Walk', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '125', 'identifier' => 'fa.hedayatfarfooladvand', 'language' => 'fa', 'name' => 'Fooladvand - Hedayatfar', 'english_name' => 'Fooladvand - Hedayatfar', 'format' => 'audio', 'type' => 'translation', 'direction' => null],
            ['id' => '126', 'identifier' => 'ar.parhizgar', 'language' => 'ar', 'name' => 'شهریار پرهیزگار', 'english_name' => 'Parhizgar', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '127', 'identifier' => 'ur.khan', 'language' => 'ur', 'name' => 'Shamshad Ali Khan', 'english_name' => 'Shamshad Ali Khan', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '128', 'identifier' => 'zh.chinese', 'language' => 'zh', 'name' => '中文', 'english_name' => 'Chinese', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '129', 'identifier' => 'fr.leclerc', 'language' => 'fr', 'name' => 'Youssouf Leclerc', 'english_name' => 'Youssouf Leclerc', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '130', 'identifier' => 'quran-kids', 'language' => 'ar', 'name' => 'القرآن الكريم للأطفال', 'english_name' => 'Kids', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '131', 'identifier' => 'quran-corpus-qd', 'language' => 'ar', 'name' => 'Corpus', 'english_name' => 'Corpus', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '132', 'identifier' => 'si.naseemismail', 'language' => 'si', 'name' => 'Naseem Ismail', 'english_name' => 'Naseem Isamil and Masoor Maulana, Kaleel', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '133', 'identifier' => 'quran-buck', 'language' => 'ar', 'name' => 'Buck', 'english_name' => 'Buck', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '134', 'identifier' => 'zh.mazhonggang', 'language' => 'zh', 'name' => 'Ma Zhong Gang', 'english_name' => '马仲刚', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '135', 'identifier' => 'ar.aymanswoaid', 'language' => 'ar', 'name' => 'أيمن سويد', 'english_name' => 'Ayman Sowaid', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '136', 'identifier' => 'quran-wordbyword-2', 'language' => 'ar', 'name' => 'معاني مفردات القرآن ولفظها (wordbyword-2]', 'english_name' => 'Word by Word Transaltion by Dr. Shehnaz Shaikh', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '137', 'identifier' => 'quran-unicode', 'language' => 'ar', 'name' => 'القرآن الكريم برسم العثماني (unicode]', 'english_name' => 'Unicode Quran text from Khaled Hosny', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '138', 'identifier' => 'quran-uthmani-quran-academy', 'language' => 'ar', 'name' => 'القرآن الكريم برسم العثماني (quran-academy]', 'english_name' => 'Modified Quran Uthmani Text from the Quran Academy to work with the Kitab font', 'format' => 'text', 'type' => 'quran', 'direction' => 'rtl'],
            ['id' => '139', 'identifier' => 'ba.mehanovic', 'language' => 'ba', 'name' => 'Kur\'an - sa prevodom (značenja] na bosanski jezik, utemeljen na Ibn Kesirovom tumačenju, i kratki komentar', 'english_name' => 'Quran translation by Muhamed Mehanovic', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '140', 'identifier' => 'ru.kuliev-audio', 'language' => 'ru', 'name' => 'Elmir Kuliev by 1MuslimApp', 'english_name' => 'Elmir Kuliev by 1MuslimApp', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '141', 'identifier' => 'en.itani', 'language' => 'en', 'name' => 'Clear Qur\'an - Talal Itani', 'english_name' => 'Clear Qur\'an by Talal Itani', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '142', 'identifier' => 'ar.qurtubi', 'language' => 'ar', 'name' => 'تفسير القرطبي', 'english_name' => 'Tafseer Al Qurtubi', 'format' => 'text', 'type' => 'tafsir', 'direction' => 'rtl'],
            ['id' => '143', 'identifier' => 'ar.miqbas', 'language' => 'ar', 'name' => 'تنوير المقباس من تفسير بن عباس', 'english_name' => 'Tafseer Tanwir al-Miqbas', 'format' => 'text', 'type' => 'tafsir', 'direction' => 'rtl'],
            ['id' => '144', 'identifier' => 'ar.waseet', 'language' => 'ar', 'name' => 'الـتـفـسـيـر الـوسـيـط', 'english_name' => 'Tafseer Al-Waseet', 'format' => 'text', 'type' => 'tafsir', 'direction' => 'rtl'],
            ['id' => '145', 'identifier' => 'ar.baghawi', 'language' => 'ar', 'name' => 'تفسير البغوي', 'english_name' => 'Tafseer Al-Baghawi', 'format' => 'text', 'type' => 'tafsir', 'direction' => 'rtl'],
            ['id' => '146', 'identifier' => 'my.ghazi', 'language' => 'my', 'name' => 'Ghazi Muhammed Hashim', 'english_name' => 'Translation by Ghazi Muhammed Hashim', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '147', 'identifier' => 'en.mubarakpuri', 'language' => 'en', 'name' => 'Mubarakpuri', 'english_name' => 'Mubarakpuri', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '148', 'identifier' => 'am.sadiq', 'language' => 'am', 'name' => 'ሳዲቅ & ሳኒ ሐቢብ', 'english_name' => 'ሳዲቅ & ሳኒ ሐቢብ', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '149', 'identifier' => 'ber.mensur', 'language' => 'ber', 'name' => 'At Mensur', 'english_name' => 'At Mensur', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '150', 'identifier' => 'bn.hoque', 'language' => 'bn', 'name' => 'জহুরুল হক', 'english_name' => 'জহুরুল হক', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '151', 'identifier' => 'en.qarai', 'language' => 'en', 'name' => 'Qarai', 'english_name' => 'Qarai', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '152', 'identifier' => 'en.wahiduddin', 'language' => 'en', 'name' => 'Wahiduddin Khan', 'english_name' => 'Wahiduddin Khan', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '153', 'identifier' => 'es.bornez', 'language' => 'es', 'name' => 'Bornez', 'english_name' => 'Bornez', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '154', 'identifier' => 'es.garcia', 'language' => 'es', 'name' => 'Garcia', 'english_name' => 'Garcia', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '155', 'identifier' => 'ur.najafi', 'language' => 'ur', 'name' => 'محمد حسین نجفی', 'english_name' => 'محمد حسین نجفی', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '156', 'identifier' => 'fa.gharaati', 'language' => 'fa', 'name' => 'قرائتی', 'english_name' => 'قرائتی', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '157', 'identifier' => 'fa.sadeqi', 'language' => 'fa', 'name' => 'صادقی تهرانی', 'english_name' => 'صادقی تهرانی', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '158', 'identifier' => 'fa.safavi', 'language' => 'fa', 'name' => 'صفوی', 'english_name' => 'صفوی', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '159', 'identifier' => 'id.jalalayn', 'language' => 'id', 'name' => 'Tafsir Jalalayn', 'english_name' => 'Tafsir Jalalayn', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '160', 'identifier' => 'ml.karakunnu', 'language' => 'ml', 'name' => 'കാരകുന്ന് & എളയാവൂര്', 'english_name' => 'കാരകുന്ന് & എളയാവൂര്', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '161', 'identifier' => 'nl.leemhuis', 'language' => 'nl', 'name' => 'Leemhuis', 'english_name' => 'Leemhuis', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '162', 'identifier' => 'nl.siregar', 'language' => 'nl', 'name' => 'Siregar', 'english_name' => 'Siregar', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '163', 'identifier' => 'ps.abdulwali', 'language' => 'ps', 'name' => 'عبدالولي', 'english_name' => 'عبدالولي', 'format' => 'text', 'type' => 'translation', 'direction' => 'rtl'],
            ['id' => '164', 'identifier' => 'ru.kuliev-alsaadi', 'language' => 'ru', 'name' => 'Кулиев + ас-Саади', 'english_name' => 'Кулиев + ас-Саади', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '165', 'identifier' => 'ru.kuliev-audio-2', 'language' => 'ru', 'name' => 'Elmir Kuliev 2 by 1MuslimApp', 'english_name' => 'Elmir Kuliev 2 by 1MuslimApp', 'format' => 'audio', 'type' => 'versebyverse', 'direction' => null],
            ['id' => '166', 'identifier' => 'ce.magomedov', 'language' => 'ce', 'name' => 'Chechen by Magomedov', 'english_name' => 'Chechen by Magomedov', 'format' => 'text', 'type' => 'translation', 'direction' => 'ltr'],
            ['id' => '167', 'identifier' => 'ru.transliteration', 'language' => 'ru', 'name' => 'Транскрипция', 'english_name' => 'Russian Transliteration', 'format' => 'text', 'type' => 'transliteration', 'direction' => 'ltr'],

        ];

        DB::table('editions')->insert($editions);
        $this->command->info('Editions seeded successfully!');
    }
}
